CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TYPE organization_type AS ENUM ('SHIPPER','CARRIER','BROKER');
CREATE TYPE load_status AS ENUM ('DRAFT','VALIDATING','QUOTED','SHIPPER_ACCEPTED','SEARCHING','OFFERING','BOOKED','DISPATCHED','AT_PICKUP','LOADED','IN_TRANSIT','AT_DELIVERY','DELIVERED','POD_RECEIVED','INVOICED','SETTLED','CLOSED','EXCEPTION','CANCELLED');
CREATE TYPE offer_status AS ENUM ('PENDING','OPENED','ACCEPTED','DECLINED','COUNTERED','EXPIRED','CANCELLED');
CREATE TYPE exception_status AS ENUM ('OPEN','ACKNOWLEDGED','RESOLVED');
CREATE TYPE quote_status AS ENUM ('OPEN','ACCEPTED','EXPIRED','CANCELLED');

CREATE TABLE organizations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),type organization_type NOT NULL,legal_name text NOT NULL,dba_name text,status text NOT NULL DEFAULT 'ACTIVE',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE shippers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid UNIQUE NOT NULL REFERENCES organizations(id),credit_status text NOT NULL DEFAULT 'PENDING',credit_limit numeric(12,2),payment_terms_days integer NOT NULL DEFAULT 30,risk_score integer NOT NULL DEFAULT 0 CHECK (risk_score BETWEEN 0 AND 100));
CREATE TABLE carriers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid UNIQUE NOT NULL REFERENCES organizations(id),usdot_number text,mc_number text,authority_status text NOT NULL DEFAULT 'PENDING',insurance_status text NOT NULL DEFAULT 'PENDING',onboarding_status text NOT NULL DEFAULT 'PENDING',fraud_score integer NOT NULL DEFAULT 0 CHECK (fraud_score BETWEEN 0 AND 100),performance_score numeric(5,2) NOT NULL DEFAULT 50,verified_at timestamptz,last_verified_at timestamptz,verification_expires_at timestamptz,verified_legal_name text,legal_name_verified boolean NOT NULL DEFAULT false,banking_changed_at timestamptz,dispatch_phone text,dispatch_email text,UNIQUE(usdot_number),UNIQUE(mc_number));
CREATE TABLE carrier_invites (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),public_token uuid UNIQUE NOT NULL DEFAULT gen_random_uuid(),contact_email text,status text NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','SUBMITTED','EXPIRED','REVOKED')),carrier_id uuid REFERENCES carriers(id),expires_at timestamptz NOT NULL,submitted_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX carrier_invites_token_idx ON carrier_invites(public_token);
CREATE TABLE carrier_equipment_profiles (carrier_id uuid NOT NULL REFERENCES carriers(id) ON DELETE CASCADE,equipment_type text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY (carrier_id,equipment_type));
CREATE TABLE carrier_verification_checks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),carrier_id uuid NOT NULL REFERENCES carriers(id) ON DELETE CASCADE,provider text NOT NULL DEFAULT 'WEBHOOK',status text NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','PROCESSING','WAITING_PROVIDER','PASSED','REVIEW','FAILED')),attempts integer NOT NULL DEFAULT 0,next_attempt_at timestamptz NOT NULL DEFAULT now(),authority_status text,insurance_status text,verified_legal_name text,legal_name_match boolean,result jsonb NOT NULL DEFAULT '{}'::jsonb,last_error text,requested_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX carrier_verification_queue_idx ON carrier_verification_checks(status,next_attempt_at);
CREATE INDEX carrier_verification_carrier_idx ON carrier_verification_checks(carrier_id,created_at DESC);
CREATE TABLE drivers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),carrier_id uuid NOT NULL REFERENCES carriers(id),name text NOT NULL,phone text,email text,status text NOT NULL DEFAULT 'ACTIVE');
CREATE TABLE trucks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),carrier_id uuid NOT NULL REFERENCES carriers(id),driver_id uuid REFERENCES drivers(id),unit_number text NOT NULL,equipment_type text NOT NULL,current_location geography(Point,4326),available_at timestamptz,status text NOT NULL DEFAULT 'AVAILABLE',location_updated_at timestamptz);
CREATE INDEX trucks_location_gix ON trucks USING gist(current_location);

CREATE TABLE quotes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),reference_number text UNIQUE NOT NULL,shipper_id uuid REFERENCES shippers(id),status quote_status NOT NULL DEFAULT 'OPEN',origin_city text NOT NULL,origin_state text NOT NULL,origin_location geography(Point,4326),destination_city text NOT NULL,destination_state text NOT NULL,destination_location geography(Point,4326),pickup_start timestamptz NOT NULL,equipment_type text NOT NULL,estimated_miles numeric(8,1) NOT NULL,weight_lbs integer,commodity text,cargo_value numeric(12,2),expected_carrier_cost numeric(12,2) NOT NULL,target_carrier_rate numeric(12,2) NOT NULL,max_carrier_rate numeric(12,2) NOT NULL,shipper_price numeric(12,2) NOT NULL,target_margin_pct numeric(5,2) NOT NULL,pricing_notes jsonb NOT NULL DEFAULT '[]'::jsonb,expires_at timestamptz NOT NULL,accepted_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE loads (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),quote_id uuid REFERENCES quotes(id),reference_number text UNIQUE NOT NULL,shipper_id uuid REFERENCES shippers(id),status load_status NOT NULL DEFAULT 'DRAFT',origin_city text NOT NULL,origin_state text NOT NULL,origin_location geography(Point,4326),destination_city text NOT NULL,destination_state text NOT NULL,destination_location geography(Point,4326),pickup_start timestamptz NOT NULL,pickup_end timestamptz,delivery_start timestamptz,delivery_end timestamptz,equipment_type text NOT NULL,weight_lbs integer,commodity text,cargo_value numeric(12,2),shipper_rate numeric(12,2),target_carrier_rate numeric(12,2),max_carrier_rate numeric(12,2),automation_mode text NOT NULL DEFAULT 'AUTOPILOT',risk_level text NOT NULL DEFAULT 'NORMAL',created_at timestamptz NOT NULL DEFAULT now(),booked_at timestamptz,delivered_at timestamptz,closed_at timestamptz);
CREATE UNIQUE INDEX loads_quote_id_unique ON loads(quote_id) WHERE quote_id IS NOT NULL;
CREATE INDEX loads_status_idx ON loads(status);
CREATE INDEX loads_origin_gix ON loads USING gist(origin_location);
CREATE TABLE load_matches (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),load_id uuid NOT NULL REFERENCES loads(id) ON DELETE CASCADE,carrier_id uuid NOT NULL REFERENCES carriers(id),truck_id uuid REFERENCES trucks(id),deadhead_miles numeric(8,2),proposed_rate numeric(12,2),reliability_score numeric(5,2),fraud_score numeric(5,2),match_score numeric(5,2),eligible boolean NOT NULL DEFAULT false,rejection_reasons jsonb NOT NULL DEFAULT '[]'::jsonb,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX load_matches_rank_idx ON load_matches(load_id,eligible,match_score DESC);
CREATE TABLE offers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),load_id uuid NOT NULL REFERENCES loads(id) ON DELETE CASCADE,carrier_id uuid NOT NULL REFERENCES carriers(id),truck_id uuid REFERENCES trucks(id),public_token uuid NOT NULL DEFAULT gen_random_uuid(),initial_rate numeric(12,2) NOT NULL,current_rate numeric(12,2) NOT NULL,maximum_rate numeric(12,2) NOT NULL,status offer_status NOT NULL DEFAULT 'PENDING',sent_at timestamptz NOT NULL DEFAULT now(),expires_at timestamptz,opened_at timestamptz,responded_at timestamptz);
CREATE UNIQUE INDEX offers_public_token_unique ON offers(public_token);
CREATE TABLE bookings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),load_id uuid UNIQUE NOT NULL REFERENCES loads(id),carrier_id uuid NOT NULL REFERENCES carriers(id),driver_id uuid REFERENCES drivers(id),truck_id uuid REFERENCES trucks(id),carrier_rate numeric(12,2) NOT NULL,booked_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE load_events (id bigserial PRIMARY KEY,load_id uuid NOT NULL REFERENCES loads(id) ON DELETE CASCADE,event_type text NOT NULL,event_time timestamptz NOT NULL DEFAULT now(),source text NOT NULL DEFAULT 'SYSTEM',location geography(Point,4326),metadata jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE INDEX load_events_timeline_idx ON load_events(load_id,event_time DESC);
CREATE TABLE exceptions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),load_id uuid REFERENCES loads(id),severity text NOT NULL,category text NOT NULL,description text NOT NULL,recommended_action text,status exception_status NOT NULL DEFAULT 'OPEN',created_at timestamptz NOT NULL DEFAULT now(),resolved_at timestamptz);
CREATE INDEX exceptions_open_idx ON exceptions(status,severity,created_at DESC);
CREATE TABLE automation_decisions (id bigserial PRIMARY KEY,load_id uuid REFERENCES loads(id),decision_type text NOT NULL,inputs jsonb NOT NULL DEFAULT '{}'::jsonb,rules_used jsonb NOT NULL DEFAULT '{}'::jsonb,decision jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE outbox_messages (id bigserial PRIMARY KEY,load_id uuid REFERENCES loads(id) ON DELETE CASCADE,carrier_id uuid REFERENCES carriers(id),channel text NOT NULL,recipient text NOT NULL,template text NOT NULL,payload jsonb NOT NULL DEFAULT '{}'::jsonb,status text NOT NULL DEFAULT 'PENDING',attempts integer NOT NULL DEFAULT 0,available_at timestamptz NOT NULL DEFAULT now(),sent_at timestamptz,last_error text,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX outbox_pending_idx ON outbox_messages(status,available_at);
