import { NextResponse } from "next/server";
import { requireApiRole } from "@/lib/auth";
import { getPool } from "@/lib/db";
import { buildInvoicePdf } from "@/lib/invoice-pdf";

function money(value: unknown) {
  return `$${Number(value ?? 0).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

export async function GET(_request: Request, context: { params: Promise<{ id: string }> }) {
  const auth = await requireApiRole(["STAFF"]);
  if (!auth.identity) return NextResponse.json({ error: auth.error }, { status: auth.status });

  const { id } = await context.params;
  const { rows } = await getPool().query(
    `SELECT i.invoice_number,i.amount,i.status,i.issued_at,i.due_at,i.paid_at,
            l.reference_number,l.origin_city,l.origin_state,l.destination_city,l.destination_state,
            so.legal_name shipper_name,co.legal_name carrier_name,p.amount carrier_amount
     FROM shipper_invoices i
     JOIN loads l ON l.id=i.load_id
     JOIN shippers s ON s.id=i.shipper_id
     JOIN organizations so ON so.id=s.organization_id
     LEFT JOIN carrier_payables p ON p.load_id=l.id
     LEFT JOIN carriers c ON c.id=p.carrier_id
     LEFT JOIN organizations co ON co.id=c.organization_id
     WHERE i.id=$1`,
    [id]
  );
  const invoice = rows[0];
  if (!invoice) return NextResponse.json({ error: "Invoice not found." }, { status: 404 });

  const lines = [
    "ARBORLINE LOGISTICS",
    "FREIGHT INVOICE",
    "",
    `Invoice: ${invoice.invoice_number}`,
    `Load: ${invoice.reference_number}`,
    `Bill to: ${invoice.shipper_name}`,
    `Lane: ${invoice.origin_city}, ${invoice.origin_state} -> ${invoice.destination_city}, ${invoice.destination_state}`,
    `Invoice amount: ${money(invoice.amount)}`,
    `Issued: ${new Date(invoice.issued_at).toLocaleDateString("en-US")}`,
    `Due: ${new Date(invoice.due_at).toLocaleDateString("en-US")}`,
    `Status: ${invoice.status}`,
    "",
    "This invoice was generated by Arborline Logistics.",
    "Payment instructions are supplied separately through approved billing channels."
  ];

  const pdf = buildInvoicePdf(lines);
  return new Response(pdf, {
    status: 200,
    headers: {
      "content-type": "application/pdf",
      "content-disposition": `inline; filename=\"${String(invoice.invoice_number).replace(/[^a-zA-Z0-9-]/g, "_")}.pdf\"`,
      "cache-control": "private, no-store"
    }
  });
}
